### ISSUE TITLE
[BUG] Anvil search is broken on 1.21.1

### ISSUE THREAD

**Issue by virustotalop** [ProdPreva1l/Fadah#11]
**Describe the bug**
The anvil search menu is broken on 1.21.1,

**To Reproduce**
1. Run /ah
2. Click on search button
3. Error is thrown

**Expected behavior**
Search menu should come up

**Screenshots**
![image](https://github.com/user-attachments/assets/98fe0fe8-dbef-452e-b615-32516498a792)

**Environment (please complete the following information):**
 - OS - Ubuntu
 - Server Type - paper
 - Server Version - 1.21.1
 - Plugin Version - 2.5.0

**Additional context**
It looks like the dependency is outdated and it should be fixed on the newest version at least when looking at the commits on the anvil gui repo.

**Comment by ProdPreva1l** [comment]
i will update this dependancy next update dont worry
