### ISSUE TITLE
[BUG] Listings leave designated GUI

### ISSUE THREAD

**Issue by LaPiedraOMG** [ProdPreva1l/Fadah#2]
When there are many listings, they go outside the designated gui

1. Make a lot of listings
2. Use the command /ah, look how they don't follow the order of listings

![bug](https://github.com/ProdPreva1l/Fadah/assets/158183508/b06d5e1f-5c01-46db-ada6-944c9dd9a5ba)

**Expected behavior**
Keep them in the box where the listings should be

**Environment (please complete the following information):**
 - OS [e.g. UBUNTU]
 - Server Type [Paper]
 - Server Version [1.19.4]
 - Plugin Version [Latest Release]
 
When will you update the plugin?

**Comment by ProdPreva1l** [comment]
Just to confirm this is version 1.6.5?

**Comment by ProdPreva1l** [comment]
To answer your question though i have a big update planned to release soon

**Comment by LaPiedraOMG** [comment]
> Just to confirm this is version 1.6.5?

Yes

**Comment by ProdPreva1l** [comment]
I can't exactly fix it for that build specifically but if you are able to wait around 2-3 days ill be releasing version 2.0 with a bunch of new features and a rework of the GUI system which allows you to control the bounds of the listing slots aswell as change the layout of the entire menu

**Comment by LaPiedraOMG** [comment]
I can wait, this is one of the few auction plugins that are good; thanks for the support : )

**Comment by ProdPreva1l** [comment]
Appreciate the support!

**Comment by ProdPreva1l** [comment]
fixed in latest release
