### ISSUE TITLE
Create a wiki for the plugin [FEATURE]

### ISSUE THREAD

**Issue by ChrisTVH** [ProdPreva1l/Fadah#4]
Well, I want a wiki for the plugin, to explain things for those who don't know much about the database and for me in my case how the menus work.
I don't know how to hide the attributes of the objects in this plugin, and I don't have a wiki or discord to consult.

Edit: If I just realized that there is discord, they should make it more distinguishable.

**Comment by ChrisTVH** [comment]
And also doubts arise, what do you mean by bedrock support?
Do you mean that it has menus for bedrock? or is it something else.

**Comment by ProdPreva1l** [comment]
> And also doubts arise, what do you mean by bedrock support? Do you mean that it has menus for bedrock? or is it something else.

Bedrock support means most features work for bedrock players, im thinking of adding a full bedrock compat mode in the future

**Comment by ChrisTVH** [comment]
> > And also doubts arise, what do you mean by bedrock support? Do you mean that it has menus for bedrock? or is it something else.
> 
> Bedrock support means most features work for bedrock players, im thinking of adding a full bedrock compat mode in the future

If you are going to do it, don't do it through geysermc, do it through its floodgate api, so that it can work correctly in networks.
This will allow you to make dedicated menus for bedrock and to know if a player is java or bedrock when running /ah.

**Comment by ProdPreva1l** [comment]
Thanks for the info, ill look into it!

**Comment by ProdPreva1l** [comment]
Docs have been made! https://docs.vote-preva1l.today/

**Comment by ChrisTVH** [comment]
> Docs have been made! https://docs.vote-preva1l.today/

Yes, I saw that you published it in your discord, but when I saw it, it said coming soon in the sections.
It's still going on but it looks great!

**Comment by ProdPreva1l** [comment]
I am going to write up a few setup guides today, so stay put!

**Comment by ChrisTVH** [comment]
> I am going to write up a few setup guides today, so stay put!

These days I'm very sick, but when I have time I will make the wiki in my language too, if I'm allowed.
